import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0f1419",
        surface: "#0f1419",
        "surface-dim": "#0f1419",
        "surface-bright": "#353a3f",
        "surface-container-lowest": "#0a0f14",
        "surface-container-low": "#171c21",
        "surface-container": "#1b2025",
        "surface-container-high": "#252a30",
        "surface-container-highest": "#30353b",
        "surface-variant": "#30353b",
        "on-surface": "#dee3ea",
        "on-surface-variant": "#ccc3d8",
        "on-background": "#dee3ea",
        "inverse-surface": "#dee3ea",
        "inverse-on-surface": "#2c3136",
        outline: "#958da1",
        "outline-variant": "#4a4455",
        primary: "#d2bbff",
        "primary-container": "#7c3aed",
        "on-primary": "#3f008e",
        "on-primary-container": "#ede0ff",
        "primary-fixed": "#eaddff",
        "primary-fixed-dim": "#d2bbff",
        "on-primary-fixed": "#25005a",
        "on-primary-fixed-variant": "#5a00c6",
        "inverse-primary": "#732ee4",
        secondary: "#c1c6da",
        "secondary-container": "#414657",
        "on-secondary": "#2b3040",
        "on-secondary-container": "#b0b4c8",
        "secondary-fixed": "#dee2f7",
        "secondary-fixed-dim": "#c1c6da",
        "on-secondary-fixed": "#161b2a",
        "on-secondary-fixed-variant": "#414657",
        tertiary: "#ffb784",
        "tertiary-container": "#a15100",
        "on-tertiary": "#4f2500",
        "on-tertiary-container": "#ffe0cd",
        "tertiary-fixed": "#ffdcc6",
        "tertiary-fixed-dim": "#ffb784",
        "on-tertiary-fixed": "#301400",
        "on-tertiary-fixed-variant": "#713700",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

export default config;
