"""ContractChunk model — represents a text chunk with vector embeddings.

Each contract document is extracted and split into deterministic text chunks.
Each chunk contains its text content, index, optional token count, and
vector embedding generated by an embedding model.

The org_id column is present for Row-Level Security (tenant_isolation policy).
A uniqueness constraint on (contract_id, version_id, chunk_index) ensures idempotency.
"""

import uuid
from datetime import datetime

from pgvector.sqlalchemy import Vector
from sqlalchemy import DateTime, ForeignKey, Integer, Text, UniqueConstraint, func
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class ContractChunk(Base):
    """Extracted text chunk of a contract document with vector embeddings.

    Attributes:
        id: Primary key (UUID).
        contract_id: FK to the parent contract.
        version_id: FK to the specific contract version.
        org_id: FK to organization (RLS filter).
        chunk_index: 0-indexed position of the chunk in the document.
        content: Extracted text content of the chunk.
        token_count: Number of tokens in the chunk (optional).
        embedding: Vector embedding (1536 dimensions).
        created_at: Row creation timestamp.
    """

    __tablename__ = "contract_chunks"
    __table_args__ = (
        UniqueConstraint(
            "contract_id",
            "version_id",
            "chunk_index",
            name="uq_contract_chunk_index",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    contract_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("contracts.id", ondelete="CASCADE"),
        index=True,
    )
    version_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("contract_versions.id", ondelete="CASCADE"),
        index=True,
    )
    org_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("organizations.id", ondelete="CASCADE"),
        index=True,
    )
    chunk_index: Mapped[int] = mapped_column(Integer)
    content: Mapped[str] = mapped_column(Text)
    token_count: Mapped[int | None] = mapped_column(Integer, nullable=True, default=None)
    embedding: Mapped[list[float] | None] = mapped_column(Vector(1536), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
